### ISSUE TITLE
Create database schema and server resources

### ISSUE THREAD

**Issue by jaythomas** [JTCC-Programming-Club/weather-station#11]
This is the data structure we talked about in week 6. Take the sample api on the [`api`](https://github.com/JTCC-Programming-Club/weather-station/tree/593ad67c912583c04199c8d52e741adcf3b0d94c) branch and make it so!

- [x] stations:
  - id: Uuid
  - label: Varchar
  - key: Varchar
- [x] sensors:
  - id: Uuid
  - alias: Varchar
  - label: Varchar
  - type_id: Uuid
  - station_id: Uuid
  - created_at: Timestamp
  - updated_at: Timestamp
- [x] measurements:
  - id: Uuid
  - value: Numeric
  - sensor_id: Uuid
  - created_at: Timestamp
- [x] sensor_types:
  - id: Uuid
  - label: Varchar
  - description: Varchar

**Comment by jaythomas** [comment]
Oops. Closed by mistake.

**Comment by SuperShadowPlay** [comment]
Had a bit of time on my hands and implemented all of the tables above in the branch `expand-api`. I'm not sure how exactly we want to merge it in (if it is acceptable of course), since `trevor-api` has not been merged in. Should we merge `trevor-api` and then `expand-api` (once the latter has been fully ironed out) or just forget about `trevor-api`?

**Comment by jaythomas** [comment]
It looks like you based `expand-api` off the `trevor-api` branch, meaning `expand-api` contains everything `trevor-api` did and more. So `trevor-api` is redundant at this point and the pull request could be closed in favor of opening a pull request of the `expand-api` branch (pointed to the original `api` branch of course).

**Comment by jaythomas** [comment]
Will open a separate GH issue to tie in the associations.
